### PR TITLE
Updating to v1.24 of Docker engine api

### PR DESCRIPTION
**Pull request by swernli**
The big kahuna.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@swernli awesome I think I'll just merge that. can you please update CHANGELOG in readme and tell me what to call this version? Should we update the nuget as well or should we do it after the transfer (I think I should transfer NuGet ownership to you as well).

**Comment by jgarverick** [comment]
This is fantastic! @ahmetalpbalkan did I read that correctly--stepping away as the primary?

**Comment by ahmetalpbalkan** [comment]
@jgarverick yes!  Windows team has developed tools to keep the API compatibility up to date with Docker codebase and they developed https://github.com/Microsoft/Docker-PowerShell/ using this. Many more Microsoft teams started to take dependency on this repo. 

We are hoping to graduate this into an official repository under Microsoft's GitHub org.

**Comment by swernli** [comment]
@ahmetalpbalkan I updated the changelog.  The version we've been using for this is 2.124 (major version bump to indicate a breaking change, and the minor version shows the Engine API it targets).  That would be my suggestion for a tag/release.

**Comment by swernli** [comment]
@jterry75 FYI :)

**Comment by jstarks** [comment]
@jterry75 Are we putting the generator in yet? We shouldn't keep that private.

**Comment by jgarverick** [comment]
That's awesome, Ahmet. Glad I could pitch in when I could. 😊 

-----Original Message-----

**Comment by ahmetalpbalkan** [comment]
@swernli @jterry75  merged and tagged. If one of you could go over the README and fix the sample code (I'm assuming something must have changed) that would be great!

@jgarverick we always appreciate your contributions!

**Comment by jterry75** [comment]
@jstarks Yes the generator is going to be added ASAP. Just wasn't ready for this PR.

**Pull request merged**
