### PR TITLE
 Resolves: #65 - Omits empty values when serializing

### PR DESCRIPTION
**Pull request by jterry75**

### CODE REVIEW

**Comment by jterry75** [comment]
@swernli - This also contains the latest model can you make sure Docker.PowerShell is not broken by any of these changes.

**Comment by jstarks** [comment]
I'd prefer a commit title other than "Resolves #65" so that the history is in git

**Comment by jterry75** [comment]
Wait you mean actually put real information into the git commit or change the tile of the PR?

**Comment by jstarks** [comment]
LGTM

**Pull request merged**
