### PR TITLE
AspNet5 libraries

### PR DESCRIPTION
**Pull request by build-your-web**

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@build-your-web what is this seriously? care to add some explanation while sending a 3000 line change that duplicates all the code we have? :smile:

**Comment by build-your-web** [comment]
AspNet5 projects can't use old projects. I created new projects with same files.
And 1 bug fix (BoolQueryStringConverter causes an exception):
https://github.com/ahmetalpbalkan/Docker.DotNet/blob/master/Docker.DotNet/Models/ListContainersParameters.cs#L96

**Comment by ahmetalpbalkan** [comment]
1. We have a package on NuGet. Can't aspnet5 just use that? If not, I'm not really fan of duplicating all the code in a separate project for a beta runtime. If you really want to do it, please try to find a common ground or write a proposal (as an issue how the work will look like).  I'm not even sure if you just copy pasted all the source code or changed anything for compatibility. I can't just review 2800 lines of code to find out what does this change involve. We can open a new branch for this work but please come up with smaller steps or at least an initial proposal declaring what the work is going to look like.

2. Please submit the bugfix as a separate PR to the existing code.

**Comment by build-your-web** [comment]
Sorry. I found what I can reference projects by nuget.

**Pull request closed without merging**
